### ISSUE TITLE
Option add url /crowd/ 

### ISSUE THREAD

**Issue by RogerSik** [alvistack/ansible-role-crowd#2]
We have Crowd manually installed where the admin interface is under crowd.example.org/crowd/ is reachable. 

With this (fanstastic :)) role we have the admin interface reachable under crowd.example.org/
Is it possible (with a variable?) to have it again reachable under /crowd/? 

crowd.example.org looks definitely better but here we would need to change dozens of Applications.

**Comment by RogerSik** [comment]
Fixed it with the variable
`crowd_catalina_context_path: "/crowd/"`

**Comment by hswong3i** [comment]
Great you get it ;-)
